"""
Elastic Compute（弹性计算）实体模型包。

按 K8s 契约来源拆分为两个物理隔离的子模块：

- :mod:`base.api.entity.elastic_compute.native` —— K8s 原生 / 通用 payload
  （PaasLabels、K8sMetadata、NamespacePayload、WorkloadPayload…）以及
  ``tests/api/elastic_compute/native/`` 对应的 ``*NativePublicParams`` /
  ``*Entity``。
- :mod:`base.api.entity.elastic_compute.extension` —— 磐基 extensions API 专有
  （Workload / Helm / Partitions / CustomResource / TenantQuota /
  PhysicalHost / …），对应 ``tests/api/elastic_compute/extensions/``。
- :mod:`base.api.entity.elastic_compute.openapi` —— openapi 侧
  ``K8s*Entity`` / ``*PublicParams``，对应 ``tests/api/elastic_compute/openapi/``。

本 ``__init__`` 统一 re-export 所有 native + extension 符号，历史 import
``from base.api.entity.elastic_compute import XxxEntity`` 保持完全向后兼容。
openapi 侧命名与 native/extension 存在冲突（如 ``WorkloadEntity``），不参与
本包顶层 re-export，请显式 ``from base.api.entity.elastic_compute.openapi
import ...`` 引用。
"""

from base.api.entity.elastic_compute.extension import (
    AppGrantEntity,
    AppGrantPublicParams,
    AppRemoveGrantEntity,
    ClusterManagerPublicParams,
    CustomResourceCreateEntity,
    CustomResourcePublicParams,
    CustomResourceUpdateEntity,
    DashboardPublicParams,
    EndpointsPublicParams,
    HarborBindClusterEntity,
    HarborBindPublicParams,
    HelmBatchUninstallEntity,
    HelmChartPublicParams,
    HelmReleaseEntity,
    HostBindPublicParams,
    ImageApiPublicParams,
    LimitRangeEntity,
    NamespaceQuotaPublicParams,
    NginxRbacPublicParams,
    NodePublicParams,
    PartitionsPublicParams,
    PhysicalHostPublicParams,
    ResourceQuotaEntity,
    SystemBindPublicParams,
    TenantQuotaBatchEntity,
    TenantQuotaPublicParams,
    WorkloadEntity,
    WorkloadPatchEntity,
    WorkloadPublicParams,
    WorkloadServiceEntity,
    WorkloadServicePortEntity,
)
from base.api.entity.elastic_compute.native import (
    ClusterRoleBindingEntity,
    ClusterRoleBindingNativePublicParams,
    ConfigMapEntity,
    ConfigMapNativePublicParams,
    ContainerPort,
    ContainerSpec,
    CrdEntity,
    CrdNativePublicParams,
    DaemonSetNativePublicParams,
    DeploymentNativePublicParams,
    HpaCpuUtilizationMetric,
    HpaNativeEntity,
    HpaNativePublicParams,
    HpaPayload,
    HpaScaleTargetRef,
    IngressHttpPath,
    IngressNativeEntity,
    IngressNativePublicParams,
    IngressPayload,
    IngressServiceBackend,
    JobEntity,
    JobNativePublicParams,
    K8sMetadata,
    LabelSelector,
    LimitRangeItem,
    LimitRangeNativeEntity,
    LimitRangePayload,
    NamespaceEntity,
    NamespaceNativePublicParams,
    NamespacePayload,
    NodeNativePublicParams,
    PaasLabels,
    PodNativeEntity,
    PodNativePublicParams,
    PodPayload,
    PodTemplate,
    PriorityClassNativeEntity,
    PriorityClassNativePublicParams,
    PriorityClassPayload,
    PvcEntity,
    PvcNativePublicParams,
    ResourceQuotaNativeEntity,
    ResourceQuotaPayload,
    RoleBindingEntity,
    RoleBindingNativePublicParams,
    SecretEntity,
    SecretNativePublicParams,
    ServiceAccountEntity,
    ServiceAccountNativePublicParams,
    ServiceEntity,
    ServiceNativePublicParams,
    StatefulSetNativePublicParams,
    WorkloadNativeEntity,
    WorkloadPayload,
)

__all__ = [
    # native: basic reusable components
    "PaasLabels",
    "LabelSelector",
    "ContainerPort",
    "ContainerSpec",
    "K8sMetadata",
    "PodTemplate",
    # native: generic K8s payload
    "NamespacePayload",
    "ResourceQuotaPayload",
    "LimitRangeItem",
    "LimitRangePayload",
    "PriorityClassPayload",
    "IngressServiceBackend",
    "IngressHttpPath",
    "IngressPayload",
    "HpaScaleTargetRef",
    "HpaCpuUtilizationMetric",
    "HpaPayload",
    "PodPayload",
    "WorkloadPayload",
    # native: PublicParams (19)
    "ServiceAccountNativePublicParams",
    "ClusterRoleBindingNativePublicParams",
    "RoleBindingNativePublicParams",
    "PvcNativePublicParams",
    "CrdNativePublicParams",
    "PodNativePublicParams",
    "JobNativePublicParams",
    "NodeNativePublicParams",
    "SecretNativePublicParams",
    "ConfigMapNativePublicParams",
    "ServiceNativePublicParams",
    "IngressNativePublicParams",
    "PriorityClassNativePublicParams",
    "HpaNativePublicParams",
    "NamespaceNativePublicParams",
    "StatefulSetNativePublicParams",
    "DeploymentNativePublicParams",
    "DaemonSetNativePublicParams",
    # native: payload entities (17)
    "ServiceAccountEntity",
    "ClusterRoleBindingEntity",
    "RoleBindingEntity",
    "PvcEntity",
    "CrdEntity",
    "PodNativeEntity",
    "JobEntity",
    "SecretEntity",
    "ConfigMapEntity",
    "ServiceEntity",
    "IngressNativeEntity",
    "PriorityClassNativeEntity",
    "HpaNativeEntity",
    "NamespaceEntity",
    "ResourceQuotaNativeEntity",
    "LimitRangeNativeEntity",
    "WorkloadNativeEntity",
    # extension
    "WorkloadPublicParams",
    "WorkloadEntity",
    "WorkloadServicePortEntity",
    "WorkloadServiceEntity",
    "WorkloadPatchEntity",
    "HelmChartPublicParams",
    "HelmReleaseEntity",
    "HelmBatchUninstallEntity",
    "PartitionsPublicParams",
    "ResourceQuotaEntity",
    "LimitRangeEntity",
    "CustomResourcePublicParams",
    "CustomResourceCreateEntity",
    "CustomResourceUpdateEntity",
    "TenantQuotaPublicParams",
    "TenantQuotaBatchEntity",
    "PhysicalHostPublicParams",
    "NamespaceQuotaPublicParams",
    "NginxRbacPublicParams",
    "SystemBindPublicParams",
    "ClusterManagerPublicParams",
    "AppGrantPublicParams",
    "AppGrantEntity",
    "AppRemoveGrantEntity",
    "DashboardPublicParams",
    "NodePublicParams",
    "HarborBindPublicParams",
    "HarborBindClusterEntity",
    "ImageApiPublicParams",
    "EndpointsPublicParams",
    "HostBindPublicParams",
]
